# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['10.2.1.11:15692']

  - job_name: 'gateway'
    static_configs:
      - targets: ['10.2.1.11:8080']

  - job_name: 'erlang-nodes'
    static_configs:
      - targets: ['10.2.1.11:9100', '10.2.1.12:9100']

  - job_name: 'workers'
    static_configs:
      - targets: ['10.2.1.11:8000']
