# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq1:15692']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'erlang-nodes'
    static_configs:
      - targets: ['orchestrator1:9100', 'orchestrator2:9100']

  - job_name: 'workers'
    static_configs:
      - targets: ['python-worker1:8000']
